import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/cla9klq8r23iw01um3b9j3rig/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      createdBy {
        id
        name
        picture
      }
      content {
        html
      }
      photo {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export const getStaticProps = async () => {
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
  };
};

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h2>NextjsとGraphQLのブログ</h2>
          <div className={styles.gridWrapper}>
            {posts.map((post) => {
              return (
                <BlogCard
                  photo={post.photo}
                  title={post.title}
                  date={post.datePublished}
                  slug={post.slug}
                  key={post.id}
                />
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
